# Generated by Django 2.1.5 on 2019-02-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='New course')),
                ('description', models.TextField(default='This is a description of the new course...')),
                ('price', models.TextField(default='99.99')),
            ],
        ),
        migrations.CreateModel(
            name='OldCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(default='This is a description of the old course...')),
                ('price', models.TextField(default='99.99')),
            ],
        ),
    ]
