# Generated by Django 2.1.5 on 2019-02-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductClass',
        ),
    ]
