# Generated by Django 2.1.5 on 2019-02-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190212_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductClass',
            new_name='Product',
        ),
    ]
